# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
julia:
  - 0.6
  - 0.5
matrix:
  allow_failures:
    - julia: nightly
notifications:
  email: false
script:
#  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
  - julia -e 'Pkg.clone(pwd())'
  - julia -e 'Pkg.test("TinyInt",coverage=true)'
after_success:
  - julia -e 'cd(Pkg.dir("TinyInt")); include(joinpath("docs", "make.jl"))'
  - julia -e 'cd(Pkg.dir("TinyInt")); Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'
  - julia -e 'cd(Pkg.dir("TinyInt")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(process_folder())'

